language: java
jdk:
- oraclejdk8
dist: trusty
install: true

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=API4KBs_kmdp-asset-repository -Ppublic -q

deploy:
  provider: script
  script: mvn deploy -DskipTests -Ppublic -s .travis.settings.xml -q
  skip_cleanup: true


addons:
  sonarcloud:
    organization: "api4kbs"
    token:
      secure: "VJ5WWSWoqcd9VvdhisPJG3jHJ864OyJv5QyNYv8WS5Bz9mm9xLu7vfMPmdTj9EBBCVzbXbj/nzO3MJhTpNu80lF04Bd3nF/exBeiIwfUW+rqLcrsrpJZCHh8OgDAijM48HYy92sEPNPiuZQujl3zgzCF70pJG4u7jKNA/5DxlDt6nIsG1+J/xmqPBbenU5IcPr7rSjikKcN4dbl9ugtM9dxBD9CgNlbdAB2rKPYY2D7idjFe6gwxTWhWgQGhl6ckyz452+Pv4k1TBHHojVJrPz4p5yNnsh47wNkl8K/DLwfJMzLb6L7H4b3MFZWOCFTQStPxsGoE88Rwmff4uUbz5CMIGeQmoOW2ru3TRhhKBSx20rc4slTxqtoJGTcTc3XcZs6rkAF4QM+AsIHlvK1jeMyn6X1/E9e2jgiXQcr7aAzI77A2o29pI3ZG/7V4FJi8/x22XOb8mYl2gAWUD9c4uyis+M5Yh6ljNzY9saERX6ZZL95Sx9SCJlsmCeScEAoFqU+HFB5Mc/gYc1LhyWSKFGCST9pgLi7qYmdixmX/UlrJYq7dY48kiewWngsg2p8+IAsrnATjSw9OI0fQvU6mgYdZXPLd8C5CcaA19LqhbdEWHf1teKa2JkCAXLD/F2yVuKM7odb8Tht0aBGneuroXKltcTKcF26lRMT/uz1ey0k="

env:
  global:
  - secure: jwKWYi6ddtpPRuQ3/8SnQEJ84bXagvk7i1fNrH2GVSZ8qZ0yf/cKO2tw/w9n0KJsny2wlQaHB/N8rV9s4sqEeN0GGQC4lUjX71avDmhOj40idgQqd/lY+COAkMOw4CKI4Rb2zDfmy96OIAWUGfC//JkxvzW/8ENU4Vwm0KP58Q2GNNrQM9t0WjGTfFH+zuyV5bSo8FQaUn12GDb6FFYro9StWlGkhxB5KJYVdMe88Vq7zeeTf7sl8OeAykvOXScPUYlTdp29F7XLJKI2vpEtzjsagyqiB6P+pOsbXHYSTrWZMP8M+ldHZPOYwwJMyII617s97PDxC/K7uT/9Oe29dEd4axBSuVjSr51Vp2cqTXToYcENP7PQv6UOMNa+gwO7V3Wdr38PPjutbj9X/p8TQAWEaMN7oLaQJwJ03LnlymkyP36o1EHfYZvKpBSMCv6L39dOk2Q3o1oijT/2dRNkB7Y7kbeW3PEOqU+Q3dEGz4QFT8any4sYAga+XDFkBqiJ/CnHsW7cExooUj8YZ4z8Vb/Cc46bZ+RYC2sZzxucZ/5iiWzNU2uKLNjFB+AJpnH6RmviCwmnMyMk9sqeQsqlUxbS+gRb1PACCqt435RpW/aCyWx3JHMEdgioSfZ+GMvsSS3kViUpXIYOKkzMKLqaV9ScN2ciVYDTM+AkADmkpKE=
  - secure: Owyz3AXkYKFdKtTjQHB5k3qGDGzs8DIR2lH90UZvh5QOYf3i4q2cbpgtRutXuY7BAy4K9v0i8QIykC8GFAFW8TppO+DJ82DGuoDKtJji5BX6AMOsMXaARygrHNei0lHep1ozYJQMa3PJ2UogmywsXLymZ2Lv4BmjeqZ3anxIhd9BKD3XuviRoflYjE6/EJdIH+jkQR+26vhEXOWlHpl7fn0hJ49q/tJaPHt3XdD/3ecozbNBzFvM+xQjLs6jQ9K1DA2x2gWP4LdA+coDQl+dwh50ABSVFLRn49S8sytjDSHsvMFso9BOcBBeO1EmVAXijeYZtccCQOa0cM8HQDI5+TExaPvy5uE+Rm7983PIxd1G1dHYrrDOE5o7gTsL6Y8rEXwMYGxANps6B5QuGI1r/At10P8brUuluQxH206pFFO4wjak7RGLs3K/NNDZ1meA3D38Yb4uqgT/8nA0CyUwidq/WjPhbc4lbU9B7Vq2Of2GXqbHlkwwvqiyha9kfqLsVpeF2koZXUqwAkF2WzsD7fPL0FUZXbZ0WZhrDhGf3RuyesjGMBS4ZPOwHdQXeZxnnTtN6i/tEqZDTlqg8NiSy857Gr91JCbDrD4/tEd1ObUakTmcx09dd1zEFn8vqTzx3KCZRkFx5R6jNyVmug0v4KrHKKKnwxa+LFlqHaToICg=
